name: Release

on:
  push:
    tags:
      - "*.*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v1

      - name: Set up Go 1.24
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
        id: go

      - name: Print version info
        id: semver
        run: |
          make version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          cache-image: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Publish to GitHub Container Registry
        env:
          REGISTRY: ghcr.io/appscode
          DOCKER_TOKEN: ${{ secrets.LGTM_GITHUB_TOKEN }}
          USERNAME: 1gtm
          APPSCODE_ENV: prod
        run: |
          docker login ghcr.io --username ${USERNAME} --password ${DOCKER_TOKEN}
          make release COMPRESS=yes

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/offline-license-server-darwin-amd64.tar.gz
            bin/offline-license-server-darwin-arm64.tar.gz
            bin/offline-license-server-linux-amd64.tar.gz
            bin/offline-license-server-linux-arm64.tar.gz
            bin/offline-license-server-windows-amd64.zip
            bin/offline-license-server-checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
